# Generated by Django 3.1 on 2020-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0002_auto_20200918_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildScorRateC',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='加成C'),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildScorReasonC',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='加成原因C'),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildScorerC',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='勘查員C'),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemC1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemC2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemC3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemC4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemC5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusItemOtherC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueC1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueC2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueC3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueC4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueC5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='plusValueOtherC',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
