# Generated by Django 3.1 on 2020-09-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0004_yfcase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='regionalHead',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人'),
        ),
    ]
