# Generated by Django 3.1 on 2020-10-01 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yfcases', '0005_auto_20200921_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='區域負責人'),
        ),
    ]
