# Generated by Django 3.1 on 2020-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0006_auto_20201001_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseFinalDecision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='最終判定'),
        ),
    ]
